version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/scooter_rentals
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - app-network
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mongo-data:
